import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ivan\'s Portfolio 2',
  description: 'Generated by create next app',
  keywords: ['contac paget', 'ivan', 'portfolio'],
}
export default function ContactPage() {
  return (
    <>
      <span className="text-5xl">Contact Page</span>
    </>
  )
}
