import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ivan\'s Portfolio Pricing',
  description: 'Generated by create next app',
  keywords: ['pricing page', 'ivan', 'portfolio'],
}
export default function PricingPage() {
  return (
    <>
      <span className="text-5xl">Pricing Page</span>
    </>
  )
  
}